### ISSUE TITLE
using @body() in routes, 'examples' of '@apiOperation()' are overwritten in DTO's 'apiProperty()' example

### ISSUE THREAD

**Issue by si-hyeon-ee** [nestjs/swagger#1073]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Hello!

If using @nestjs/swagger to describe examples in requestBody, it occur weird action.

When a default example is specified in the DTO and examples are added in `ApiOperation`

When the `@Body()` annotation is used in the route, the default example specified in the DTO is displayed in the swagger, not the added examples.

```typescript

export class User {
    @ApiProperty({
        name: "name",
        example: "default foo name example"
    })
    name: string
    @ApiProperty({
        name: "type",
        enum: ["FOO", "BAR"],
        example: "BAR"
    })
    type: "FOO" | "BAR"
    @ApiProperty({
        name: "age",
        example: 10
    })
    age: number
}


@ApiExtraModels(User)
@Controller()
export class AppController {

    @ApiOperation({
        description: "with body annotation",
        requestBody: {
            description: "User body Example",
            required: true,
            content: {
                "application/json": {
                    schema: { $ref: getSchemaPath(User) },
                    examples: {
                        "Foo User": {
                            value: {
                                name: "foo name diffrent",
                                age: 20,
                                type: "FOO"
                            } as User,
                            description: "This is Foo user Example",
                        },
                        "Bar User": {
                            value: {
                                name: "bar name diffrent",
                                age: 30,
                                type: "BAR"
                            } as User,
                            description: "This is Bar user Example",
                        }
                    }
                }
            }
        }
    })
    @Post("/with")
    withBodyAnnotation(@Body() payload: User) {
        return payload
    }

    @ApiOperation({
        description: "with body annotation",
        requestBody: {
            description: "User body Example",
            required: true,
            content: {
                "application/json": {
                    schema: { $ref: getSchemaPath(User) },
                    examples: {
                        "Foo User": {
                            value: {
                                name: "foo name diffrent",
                                age: 20,
                                type: "FOO"
                            } as User,
                            description: "This is Foo user Example",
                        },
                        "Bar User": {
                            value: {
                                name: "bar name diffrent",
                                age: 30,
                                type: "BAR"
                            } as User,
                            description: "This is Bar user Example",
                        }
                    }
                }
            }
        }
    })
    @Post("/without")
    withOuthBodyAnnotation(@Req() request: Request) {
        return request.body
    }
}
```

## Expected behavior

I think that Even with the @Body() annotation, if "examples" are specified, "examples" should appear in swagger.

Currently, if need to apply swagger examples, using `@Req() request:Request // req.body` instead of `@Body()`.

If these actions are intended, i will close this issue.

## Minimal reproduction of the problem with instructions

https://github.com/si-hyeon-ee/reports-nestjs-swagger-body-examples

## Environment

<pre><code>
Nest version: "^7.5.1"

 
For Tooling issues:
- Node version: v14.14.0  
- Platform:  Windows 

Others: "@nestjs/swagger": "^4.7.5",

</code></pre>

some Documentation : https://www.viralpatel.net/openapi-multiple-examples/

**Comment by konne** [comment]
Hi,
thanks for the workaround but I see the same issue.

I think here two possible ways. One is to allow an ApiDecorator for the @Body to define an own schema.
The second is to take care a response schema overrules the @Body Schema

bye
Konrad

**Comment by kamilmysliwiec** [comment]
There's currently no bandwidth to fix this issue/implement this feature, unfortunately. Since we don't plan to address this in the foreseeable future, I'm gonna close this issue.

**Comment by konne** [comment]
@si-hyeon-ee 

What I found out is that 

```
@ApiBody({
    schema: {
     ...
    },
 @Post("/with")
    withBodyAnnotation(@Body() payload: User) {
        return payload
    }
```

Should work at least for the schema. Can you please test and confirm that?

What is still open is the example part.

**Comment by konne** [comment]
@kamilmysliwiec 
Can you give me a hint for the example. I first thought that the example is just not in the typing so I tried:

```
@ApiBody({
    schema: {
      ...
    },
    examples: {
      'Foo User': {
        value: {
      ...
      },
  } as any)
```
With the as any to get it compiled. This works but I still don't get only the schema in the openapi spec.
I'm new to your sourcecode and like to contribute with an PR, but I need a small hint.

bye
Konrad

**Comment by si-hyeon-ee** [comment]
To. @konne 

The `examples` in @ApiBody didn't work.

So I implemented that part with `requestBody> content` in @ApiOperation.

As Maintainer mentioned, this issue is low urgency, so I solved it with code like this:

```typescript
export const CustomBody = createParamDecorator((data: unknown, ctx: ExecutionContext) => {
	const request = ctx.switchToHttp().getRequest() as any
	return request.body?.data ? request.body.data : request.body
})

@ApiOperation({
    //...
})
@Post("/with")
withBodyAnnotation(@CustomBody() payload: User) {
    return payload
}
```

Validation does not work for these Custom Body Decorators, so to use validation, you need to this:


```typescript
export const MyCustomBody = () =>
	createParamDecorator((data: unknown, ctx: ExecutionContext) => {
		const request = ctx.switchToHttp().getRequest() as any
		return request.body?.data ? request.body.data : request.body
	})(new ValidationPipe({ transform: true, validateCustomDecorators: true }))

@ApiOperation({
    //...
})
@Post("/with")
withBodyAnnotation(@MyCustomBody() payload: User) {
    return payload
}
```

I hope this help to you.

**Comment by konne** [comment]
@si-hyeon-ee
I made a fork of your example and with @ApiBody I can override the example that is generated out of that User class.

https://github.com/konne/reports-nestjs-swagger-body-examples/blob/9f74bf0672b960aa792a74c0361837990ca53088/src/app.controller.ts#L63

I know that this does not solve the examples problem but please can you confirm that this works.

I working at the moment for a better understanding of the @ApiDecorator and to provide here an PR that allows to change the examples beside the schema

**Comment by konne** [comment]
@si-hyeon-ee 
I got it working with ApiBody if I change the following lines:
https://github.com/nestjs/swagger/blob/53800aed1c3964d5edfd867ba116f46ccee9c4fd/lib/swagger-explorer.ts#L351
```
const keysToRemove = ['schema', 'in', 'name','examples'];
    document.root.requestBody = {
      ...omit(requestBody, keysToRemove),
      ...this.mimetypeContentWrapper.wrap(consumes, pick(requestBody, ['schema','examples']))
    };
```

and 

```
    @ApiBody({
        schema: { 
            $ref: getSchemaPath(User),
        },
        examples:
        {
            'test': {
                value: {
                    name: "EXAMPLE APIBody beside schema",
                    age: 20,
                    type: "BAR"
                } as User,
                description: "This is Bar user Example",
            }
        }
    } as any)
```

I will try to create now a PR and change the Typings so this ugly as any is not necessary.

**Comment by si-hyeon-ee** [comment]
@konne 

If you fix the examples part inside ApiBody,

I would like to write a document about the examples part of Apibody and do PR to docs.nestjs.com.

Can you help me?

**Comment by konne** [comment]
@si-hyeon-ee I have added the PR

@kamilmysliwiec can you please give feedback on this PR or merge if it already ready to merge

**Comment by cgabbadon** [comment]
Is there anything blocking the PR from @konne to be merged? This functionality would be really useful for us. Please let me know if I can support.

**Comment by si-hyeon-ee** [comment]
Project member is reviewing to can include this feature in v8 release.

> Is there anything blocking the PR from @konne to be merged? This functionality would be really useful for us. Please let me know if I can support.

**Comment by kamilmysliwiec** [comment]
Tracking this here https://github.com/nestjs/swagger/pull/1268

**Comment by laolee010126** [comment]
@si-hyeon-ee 
dose v8 means "@nestjs/swagger": "^8.x.x"  ?
I'm really need this feature but it still "@nestjs/swagger": "^5.1.4", ... cry
